jobs:
#- template: support/azure/template-build.yml  
  #parameters:
    #name: Linux_32
    #vmImage: 'ubuntu-latest'
    #cmakeDefs: '-DARCH=32'
    #installGCC32: true
- template: support/azure/template-build.yml  
  parameters:
    name: linux64
    vmImage: 'ubuntu-latest'
    cmakeDefs: '-DARCH=64'
    archiveExtension: 'tar.gz'
    cpackParameters: '-G TGZ'
- template: support/azure/template-build.yml  
  parameters:
    name: windows32
    vmImage: 'windows-2019'
    cmakeDefs: '-A Win32'
    archiveExtension: 'zip'
    cpackParameters: '-G ZIP'
- template: support/azure/template-build.yml  
  parameters:
    name: windows64
    vmImage: 'windows-2019'
    cmakeDefs: '-A x64'
    archiveExtension: 'zip'
    cpackParameters: '-G ZIP'
- template: support/azure/template-build.yml  
  parameters:
    name: macOS
    vmImage: 'macOS-10.15'
    cmakeDefs: '-DARCH=64'
    archiveExtension: 'tar.gz'
    cpackParameters: '-G TGZ'